/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithms;

import algorithms.sprint1.B;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testBclass() {
       assertFalse(B.checkParity(7, 11, -7));
    }
}
